spring:
  application:
    name: spring-ai-demos
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
#    openai:
#      api-key: ${AI_DASHSCOPE_API_KEY}
#      embedding:
#        base-url: https://dashscope.aliyuncs.com/api/v1/services/embeddings
#        api-key: ${AI_DASHSCOPE_API_KEY}
#        options:
#          model: multimodal-embedding-v1
    vectorstore:
      milvus:
        client:
          host: 192.168.3.96
          port: 19530
          username: root
          password: milvus
        embeddingDimension: 768
        indexType: IVF_FLAT
        metricType: COSINE
        embedding-field-name: embedding
        collection-name: vector_store
        database-name: default
        initialize-schema: true
